#domain-rules /apkpure.com/ -nameserver ext -ipset ext -address #6
#domain-rules /apkpure.net/ -nameserver ext -ipset ext -address #6
domain-rules /cdnpure.com/ -nameserver ext -ipset ext -address #6
#domain-rules /pureapk.com/ -nameserver ext -ipset ext -address #6
domain-rules /winudf.com/ -nameserver ext -ipset ext -address #6
