address /gdmf.apple.com/#
address /ocsp.apple.com/#
address /ocsp2.apple.com/#
address /xp.apple.com/#
address /world-gen.g.aaplimg.com/#
address /mesu.apple.com/#
address /appldnld.apple.com/#
address /swscan.apple.com/#
address /ns.itunes.apple.com/#
address /gg.apple.com/#
address /update.synology.com/#
address /jiabin.myds.me/172.16.16.2 -address #6
address /bw.4860575.xyz/172.16.16.253 -address #6
address /bw.m2y.cc/172.16.16.253 -address #6
#address /.dns.4860575.xyz/172.16.16.253 -address #6
#address /g.pan.4860575.xyz/172.16.16.253 -address #6
#address /g.pve.m2y.cc/172.16.16.253 -address #6
address /music.m2y.cc/172.16.16.253 -address
address /music.l1l1.dpdns.org/172.16.16.253 -address
address /wg.4860575.xyz/172.16.16.253 -address
address /op.lan/172.16.16.254 -address
address /ip6.arpa/#
address /in-addr.arpa/#
