domain-rules /atom.io/ -nameserver ext -ipset ext -address #6
#domain-rules /dependabot.com/ -nameserver ext -ipset ext -address #6
domain-rules /ghcr.io/ -nameserver ext -ipset ext -address #6
#domain-rules /git.io/ -nameserver ext -ipset ext -address #6
#domain-rules /github.blog/ -nameserver ext -ipset ext -address #6
#domain-rules /github.com/ -nameserver ext -ipset ext -address #6
#domain-rules /github.community/ -nameserver ext -ipset ext -address #6
domain-rules /github.dev/ -nameserver ext -ipset ext -address #6
#domain-rules /github.io/ -nameserver ext -ipset ext -address #6
domain-rules /githubapp.com/ -nameserver ext -ipset ext -address #6
#domain-rules /githubassets.com/ -nameserver ext -ipset ext -address #6
domain-rules /githubhackathon.com/ -nameserver ext -ipset ext -address #6
domain-rules /githubpreview.dev/ -nameserver ext -ipset ext -address #6
domain-rules /githubstatus.com/ -nameserver ext -ipset ext -address #6
domain-rules /githubuniverse.com/ -nameserver ext -ipset ext -address #6
#domain-rules /githubusercontent.com/ -nameserver ext -ipset ext -address #6
#domain-rules /myoctocat.com/ -nameserver ext -ipset ext -address #6
domain-rules /opensource.guide/ -nameserver ext -ipset ext -address #6
domain-rules /repo.new/ -nameserver ext -ipset ext -address #6
domain-rules /thegithubshop.com/ -nameserver ext -ipset ext -address #6
