#domain-rules /biggggg.com/ -nameserver ext -ipset ext -address #6
domain-rules /mudvod.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nbys.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nbys1.tv/ -nameserver ext -ipset ext -address #6
#domain-rules /nbyy.tv/ -nameserver ext -ipset ext -address #6
domain-rules /newpppp.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivod.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nivod0.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nivod4.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nivod5.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nivod6.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nivod7.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nivod8.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nivodi.tv/ -nameserver ext -ipset ext -address #6
domain-rules /nivod.cc/ -nameserver ext -ipset ext -address #6 
domain-rules /nivod.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivod0.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivod4.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivod5.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivod6.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivod7.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivod8.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivodi.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivodz.com/ -nameserver ext -ipset ext -address #6
domain-rules /vod360.net/ -nameserver ext -ipset ext -address #6
domain-rules /olddddd.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivod.fun/ -nameserver ext -ipset ext -address #6
domain-rules /nivod.cc/ -nameserver ext -ipset ext -address #6  
#domain-rules /nivod.fun/ -nameserver ext -ipset ext -address #6
domain-rules /nivodi1.com/ -nameserver ext -ipset ext -address #6
domain-rules /nivodi.com/ -nameserver ext -ipset ext -address #6
