domain-rules /questionmark.com/ -nameserver ext -ipset ext -address #6
domain-rules /pearsonpte.com/ -nameserver ext -ipset ext -address #6
domain-rules /edu.au/ -nameserver ext -ipset ext -address #6
domain-rules /anti-ad.net/ -nameserver ext -ipset ext -address #6
domain-rules /packagecloud.io/ -nameserver ext -ipset ext -address #6
domain-rules /debian.org/ -nameserver ext -ipset ext -address #6
domain-rules /raspberrypi.com/ -nameserver ext -ipset ext -address #6
domain-rules /z-library.rs/ -nameserver ext -ipset ext -address #6
domain-rules /51cg.fun/ -nameserver ext -ipset ext -address #6
domain-rules /cg51.com/ -nameserver ext -ipset ext -address #6
#domain-rules /v2ex.com/ -nameserver ext -ipset ext -address #6
domain-rules /zoom.us/ -nameserver ext -ipset ext -address #6
domain-rules /ubuntu.com/ -nameserver ext -ipset ext -address #6
#domain-rules /docker.com/ -nameserver ext -ipset ext -address #6
#domain-rules /docker.io/ -nameserver ext -ipset ext -address #6
domain-rules /global.quickconnect.to/ -nameserver ext -ipset ext -address #6
domain-rules /pypi.org/ -nameserver ext -ipset ext -address #6
domain-rules /pythonhosted.org/ -nameserver ext -ipset ext -address #6
domain-rules /lscr.io/ -nameserver ext -ipset ext -address #6
domain-rules /ghcr.io/ -nameserver ext -ipset ext -address #6
domain-rules /debian.org/ -nameserver ext -ipset ext -address #6
#domain-rules /bulianglin.com/ -nameserver ext -ipset ext -address #6
#domain-rules /eu.org/ -nameserver ext -ipset ext -address #6
#domain-rules /ip.sb/ -nameserver ext -ipset ext -address
#domain-rules /jable.tv/ -nameserver ext -ipset ext -address #6
domain-rules /zoom.com/ -nameserver ext -ipset ext -address #6
domain-rules /zoom.com.cn/ -nameserver ext -ipset ext -address #6
domain-rules /zoom.us/ -nameserver ext -ipset ext -address #6
#domain-rules /serv00.com/ -nameserver ext -ipset ext -address #6
domain-rules /hysteria.network/ -nameserver ext -ipset ext -address #6
#domain-rules /sagernet.org/ -nameserver ext -ipset ext -address #6
domain-rules /idev.dev/ -nameserver ext -ipset ext -address #6
domain-rules /hicairo.com/ -nameserver ext -ipset ext -address #6
domain-rules /frepai.com/ -nameserver ext -ipset ext -address #6
domain-rules /youtube4kdownloader.com/ -nameserver ext -ipset ext -address #6
#domain-rules /talkatone.com/ -nameserver ext -ipset ext -address #6
domain-rules /myunidays.hk/ -nameserver ext -ipset ext -address #6
domain-rules /51cg.fun/ -nameserver ext -ipset ext -address #6
#domain-rules /x.ai/ -nameserver ext -ipset ext -address #6
domain-rules /myunidays.hk/ -nameserver ext -ipset ext -address #6
domain-rules /myunidays.com/ -nameserver ext -ipset ext -address #6
domain-rules /thumbsnap.com/ -nameserver ext -ipset ext -address #6
domain-rules /googleapis.cn/ -nameserver ext -ipset ext -address #6
domain-rules /carsales.com.au/ -nameserver ext -ipset ext -address #6
domain-rules /captcha-delivery.com/ -nameserver ext -ipset ext -address #6
domain-rules /iyf.tv/ -nameserver ext -ipset ext -address #6
domain-rules /pipecdn.vip/ -nameserver ext -ipset ext -address #6
domain-rules /samsungconnectivity.com/ -nameserver ext -ipset ext -address #6
domain-rules /gos-gsp.io/ -nameserver ext -ipset ext -address #6
#domain-rules /samsung.com.cn/ -nameserver ext -ipset ext -address #6
#domain-rules /samsung.com/ -nameserver ext -ipset ext -address #6
domain-rules /ospserver.net/ -nameserver ext -ipset ext -address #6
domain-rules /galaxyappstore.com/ -nameserver ext -ipset ext -address #6
domain-rules /edgeone.app/ -nameserver ext -ipset ext -address #6
domain-rules /cobalt.tools/ -nameserver ext -ipset ext -address #6
domain-rules /1.fm/ -nameserver ext -ipset ext -address #6
domain-rules /v2rayssr.com/ -nameserver ext -ipset ext -address #6
