#domain-rules /fast.com/ -nameserver ext -ipset ext -address #6
domain-rules /speedtest.net.cdn.cloudflare.net/ -nameserver ext -ipset ext -address #6
domain-rules /speedtest.net/ -nameserver ext -ipset ext -address #6
domain-rules /kdatacenter.com/ -nameserver ext -ipset ext -address #6
domain-rules /i3d.net/ -nameserver ext -ipset ext -address #6
domain-rules /sonic.net/ -nameserver ext -ipset ext -address #6
domain-rules /fdcservers.net/ -nameserver ext -ipset ext -address #6
domain-rules /osakac.ac.jp/ -nameserver ext -ipset ext -address #6
domain-rules /ipa.go.jp/ -nameserver ext -ipset ext -address #6
domain-rules /fastly.net/ -nameserver ext -ipset ext -address #6
domain-rules /speed.udx.icscoe.jp/ -nameserver ext -ipset ext -address #6
domain-rules /starhub.com/ -nameserver ext -ipset ext -address #6
domain-rules /speedtest-sjc.dish-wireless.com/ -nameserver ext -ipset ext -address #6
domain-rules /snjscarc-speed01.nwrd.net/ -nameserver ext -ipset ext -address #6
domain-rules /speedtest.asymptote.cc/ -nameserver ext -ipset ext -address #6
domain-rules /sfosj0096speedtestserver01.wiline.com/ -nameserver ext -ipset ext -address #6
domain-rules /sv-ookla.geolinks.com/ -nameserver ext -ipset ext -address #6
domain-rules /vscode-sync.trafficmanager.net/ -nameserver ext -ipset ext -address #6
