#domain-rules /lf16-effectcdn.byteeffecttos-g.com/ -nameserver ext -ipset ext -address #6
domain-rules /lf16-pkgcdn.pitaya-clientai.com/ -nameserver ext -ipset ext -address #6
#domain-rules /p16-tiktokcdn-com.akamaized.net/ -nameserver ext -ipset ext -address #6
domain-rules /bytedapm.com/ -nameserver ext -ipset ext -address #6
domain-rules /bytegecko-i18n.com/ -nameserver ext -ipset ext -address #6
domain-rules /bytegecko.com/ -nameserver ext -ipset ext -address #6
#domain-rules /byteoversea.com/ -nameserver ext -ipset ext -address #6
#domain-rules /capcut.com/ -nameserver ext -ipset ext -address #6
#domain-rules /ibytedtos.com/ -nameserver ext -ipset ext -address #6
#domain-rules /ibyteimg.com/ -nameserver ext -ipset ext -address #6
domain-rules /ipstatp.com/ -nameserver ext -ipset ext -address #6
domain-rules /isnssdk.com/ -nameserver ext -ipset ext -address #6
#domain-rules /muscdn.com/ -nameserver ext -ipset ext -address #6
#domain-rules /musical.ly/ -nameserver ext -ipset ext -address #6
domain-rules /sgpstatp.com/ -nameserver ext -ipset ext -address #6
domain-rules /snssdk.com/ -nameserver ext -ipset ext -address #6
domain-rules /tik-tokapi.com/ -nameserver ext -ipset ext -address #6
#domain-rules /tiktok.com/ -nameserver ext -ipset ext -address #6
#domain-rules /tiktokcdn-us.com/ -nameserver ext -ipset ext -address #6
#domain-rules /tiktokcdn.com/ -nameserver ext -ipset ext -address #6
domain-rules /tiktokd.net/ -nameserver ext -ipset ext -address #6
domain-rules /tiktokd.org/ -nameserver ext -ipset ext -address #6
#domain-rules /tiktokv.com/ -nameserver ext -ipset ext -address #6
domain-rules /tiktokmusic.app/ -nameserver ext -ipset ext -address #6
#domain-rules /tiktokv.com/ -nameserver ext -ipset ext -address #6
#domain-rules /tiktokv.us/ -nameserver ext -ipset ext -address #6
domain-rules /tiktokw.us/ -nameserver ext -ipset ext -address #6
#domain-rules /ttwstatic.com/ -nameserver ext -ipset ext -address #6
